# Generated by Django 4.0.3 on 2022-04-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('iso2', models.CharField(max_length=20, verbose_name='ISO2')),
                ('iso3', models.CharField(max_length=20, verbose_name='ISO3')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('city_ascii', models.CharField(max_length=50, verbose_name='City ASCII')),
                ('admin_name', models.CharField(max_length=50, verbose_name='Administration Name')),
                ('lat', models.FloatField(default=0, verbose_name='Latitude')),
                ('lng', models.FloatField(default=0, verbose_name='Longitude')),
                ('population', models.CharField(max_length=15, verbose_name='Population')),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='countries_cities.countries')),
            ],
        ),
    ]
