# Generated by Django 4.0.3 on 2022-04-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_cities', '0002_alter_countries_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearestCities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city1', models.CharField(max_length=50, verbose_name='City1')),
                ('city2', models.CharField(max_length=50, verbose_name='City2')),
                ('dist', models.FloatField(default=0, verbose_name='Latitude')),
            ],
        ),
    ]
