# Generated by Django 4.0.3 on 2022-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_cities', '0003_nearestcities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestcities',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
